
spring:
  # mysql 配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver

    # url: jdbc:mysql://localhost:3306/test?useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true&characterEncoding=utf8
    # username: root
    # password: 123456

    url: jdbc:mysql://47.94.95.112:3306/fj?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowMultiQueries=true&autoReconnect=true
    username: root
    password: al@sk0987LKsd#

    type: com.alibaba.druid.pool.DruidDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
      
#mybatis是独立节点，需要单独配置
mybatis-plus:
  global-config:
    id-type: 0
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true